[DATABASES]
GAME_URL_PRIMARY = 'sqlite+aiosqlite:///var/primary/mount/games.db'
GAME_SECONDARY = 'sqlite+aiosqlite:///var/primary/mount/games.db'
GAME_TERTIRARY = 'sqlite+aiosqlite:///var/primary/mount/games.db'
USER_URL = 'sqlite+aiosqlite:///var/user.db'
